config/routes.rb
Rails.application.routes.draw do
  resources :cats

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :name, presence: true, length: { in: 1..25 }
  validates :trait, presence: true
  # validates :gender, acceptance: { accept: 'M' || 'F' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  def index
    @cats = Cat.all
  end

  def show
  end

  def edit
  end

  def update
    if @cat.update(cat_params)
      redirect_to @cat, notice: 'Cat was successfully updated.'
    else
      render :edit
    end
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
      if @cat.save
        redirect_to @cat, notice: 'Cat was successfully created.'
      else
        render :new
      end
    end
  

  def destroy
    @cat.destroy
    redirect_to cats_url, notice: 'Cat was successfully destroyed.'
  end
  
  
  private

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:name, :trait)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_form.html.erb
<%= form_for(@cat) do |cat| %>

  <div>
    <%= cat.label :name %><br>
    <%= cat.text_field :name %>
  </div>
  <div>
    <%= cat.label :trait %><br>
    <%= cat.text_area :trait %>
  </div>
  
  <div>
    <%= cat.submit 'Submit' %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Kitties</h1>

<%= render 'form' %>

app/views/cats/index.html.erb
<h1>Here is a listing of all our Cat Lady Cats!</h1>

<table>
  <thead>
    <tr>
      <th>NAME</th>
      <th>TRAIT</th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.name %></td>
        <td><%= cat.trait %></td>
        <td><%= link_to cat.name, cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure sucka?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<td><%= link_to 'New', new_cat_path %></td>

app/views/cats/new.html.erb
<h1>Make a New Kitty!</h1>

<%= render 'form' %>
<%= link_to 'Back to All the Kitties!', cats_path %>

app/views/cats/show.html.erb
<h1>This is a Show Page for <%= @cat.name %></h1>

<p>Name: <%= @cat.name %></p>
<p>Trait: <%= @cat.trait %></p>

<%= link_to 'Back to All the Kitties!', cats_path %>
<%= link_to 'Edit', edit_cat_path(@cat) %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrazyCatLady</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

<% if flash[:notice] %>
    <div><%= flash[:notice] %></div>
  <% end %>

<%= yield %>

</body>
</html>